Sample: event jsvm
slaff/Sming-jerryscript pull request #3
Opened 2021-12-01 10:15 UTC by slaff

This sample demonstrates how to run your JavaScript application as performing some action
in response to an event, input or stimulus. 
Since Sming framework itself has an [event-driven architecture](https://sming.readthedocs.io/en/latest/information/events.html) such JavaScript applications will be able to use all the advantages that Sming has in terms of CPU, RAM and power usage.

2021-12-01 10:20 UTC, slaff commented
@mikee47 Can you review also this PR when you have time?

2021-12-01 11:25 UTC, mikee47 requested changes
We should implement some C++ wrappers for handling values, etc. I've found `https://github.com/infosia/Daisy` and `https://gist.github.com/gocarlos/0c6783646074144b3af008b54a379d07` which consider at this issue.

Also some kind of wrapper mechanism which deals with parameter checking on function implementations. It might be possible to leverage C++ templates.

2021-12-01 11:25 UTC, mikee47 commented on README.rst
Suggest removing this section as page template includes a list of samples https://sming.readthedocs.io/en/latest/_inc/Sming/Libraries/jerryscript/index.html#used-by. Also note `:sample:` will only pick up framework samples - needs looking at separately.

2021-12-01 11:25 UTC, mikee47 commented on component.mk
> +COMPONENT_DOCFILES := jerryscript/docs/img/engines_high_level_design.png JerryScriptUpdate.rst
Revert - all .rst files in root directory are picked up automatically. https://sming.readthedocs.io/en/latest/information/develop/documentation.html#source-file-location

2021-12-01 11:25 UTC, mikee47 commented on samples/Event_Jsvm/component.mk
> +COMPONENT_SRCDIRS += src/
`COMPONENT_SRCDIRS := src` no /

2021-12-01 11:25 UTC, mikee47 commented on samples/Event_Jsvm/files/main.js
> +}
CR missing

2021-12-01 11:25 UTC, mikee47 commented on README.rst
> -
Missing CR

2021-12-01 11:25 UTC, mikee47 commented on samples/Event_Jsvm/src/include/vm_functions.h
> +#include <jerry-core/include/jerryscript.h>
`#include <jerryscript.h>` is sufficient

2021-12-01 11:25 UTC, mikee47 commented on samples/Event_Jsvm/src/include/vm_functions.h
> +#endif
remove

2021-12-01 11:25 UTC, mikee47 commented on samples/Event_Jsvm/src/include/vm_functions.h
> +#endif
remove

2021-12-01 11:25 UTC, mikee47 commented on samples/Event_Jsvm/src/include/vm_functions.h
> +
remove

2021-12-01 11:25 UTC, mikee47 commented on samples/Event_Jsvm/src/vm_functions.cpp
> +	//	bool is_error = jerry_value_is_error(res);
remove

2021-12-01 11:25 UTC, mikee47 commented on samples/Event_Jsvm/src/vm_functions.cpp
> +	// First Parameter - Event Name
Should check args_cnt == 2

2021-12-02 08:52 UTC, merged

2021-12-02 09:01 UTC, slaff commented
> We should implement some C++ wrappers for handling values, etc. I've found https://github.com/infosia/Daisy and https://gist.github.com/gocarlos/0c6783646074144b3af008b54a379d07 which consider at this issue. .. Also some kind of wrapper mechanism which deals with parameter checking on function implementations. It might be possible to leverage C++ templates.

I like the idea. The easier to use the better :)